[project]
name = "Morphological-Source-Code"
description = "Morphological Source Code"
authors = [{ name = "Phovos", email = "phovos@outlook.com" }]
requires-python = ">=3.14"
version = "0.4.24"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[scripts]
main = "main:main"

[project.optional-dependencies]
dev = [
    "uv",
    "pre-commit",
]

[project.scripts]
setup = "pip install -e .[dev]"
lint = "ruff ."

[tool.ruff]
line-length = 88
exclude = ["build/", "dist/", ".venv/", "imports/",]

[tool.ruff.lint]
select = ["E", "F", "W", "B"]
extend-ignore = [
    "E501",  # line too long
    "W291",  # trailing whitespace
    "W293",  # blank line contains whitespace
    "W391",  # blank line at end of file
    "D206",  # docstring whitespace errors
    "D300",  # triple double quotes on one line
]

[tool.ruff.format]
quote-style = "preserve"
skip-magic-trailing-comma = true
line-ending = "auto"

[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/seeds"]

[tool.uv]
cache-keys = [{ file = "**/*.toml" }]