# Autogenerated ByteWordOntoSpecies code
# uid: e2a348a6-9493-4b39-985a-9227ac2e8086
# parent: None
# args: ['init']

import sys
import traceback

class ByteWordOntoSpecies:
    def __init__(self, parent_id=None, args=None, uid="e2a348a6-9493-4b39-985a-9227ac2e8086"):
        self.uid = uid
        self.parent_id = parent_id
        self.args = args or []
        self.alive = True

    def run(self):
        print("Running species e2a348a6-9493-4b39-985a-9227ac2e8086 with args:", self.args)
        # Simulate survival condition
        if "fail" in self.args:
            raise RuntimeError("Simulated failure in species e2a348a6-9493-4b39-985a-9227ac2e8086")

    def __exit__(self, exc_type, exc_value, tb):
        print(f"Cleaning up species e2a348a6-9493-4b39-985a-9227ac2e8086")
        if exc_type:
            print("Exception:", exc_value)
        self.alive = False

if __name__ == "__main__":
    try:
        instance = ByteWordOntoSpecies(parent_id="None", args=['init'], uid="e2a348a6-9493-4b39-985a-9227ac2e8086")
        instance.run()
    except Exception:
        traceback.print_exc()
        sys.exit(1)
