# Autogenerated ByteWordOntoSpecies code
# uid: e13df0ea-4e4f-43eb-b09a-64ad9271b9bb
# parent: e2a348a6-9493-4b39-985a-9227ac2e8086
# args: ['fail']

import sys
import traceback

class ByteWordOntoSpecies:
    def __init__(self, parent_id=None, args=None, uid="e13df0ea-4e4f-43eb-b09a-64ad9271b9bb"):
        self.uid = uid
        self.parent_id = parent_id
        self.args = args or []
        self.alive = True

    def run(self):
        print("Running species e13df0ea-4e4f-43eb-b09a-64ad9271b9bb with args:", self.args)
        # Simulate survival condition
        if "fail" in self.args:
            raise RuntimeError("Simulated failure in species e13df0ea-4e4f-43eb-b09a-64ad9271b9bb")

    def __exit__(self, exc_type, exc_value, tb):
        print(f"Cleaning up species e13df0ea-4e4f-43eb-b09a-64ad9271b9bb")
        if exc_type:
            print("Exception:", exc_value)
        self.alive = False

if __name__ == "__main__":
    try:
        instance = ByteWordOntoSpecies(parent_id="e2a348a6-9493-4b39-985a-9227ac2e8086", args=['fail'], uid="e13df0ea-4e4f-43eb-b09a-64ad9271b9bb")
        instance.run()
    except Exception:
        traceback.print_exc()
        sys.exit(1)
