import os
import sys
import uuid
import traceback


class ByteWordOntoSpecies:
    BASE_PATH = "./byteword_species"  # storage for source+metadata

    def __init__(self, parent_id=None, args=None, uid=None):
        self.uid = uid or str(uuid.uuid4())
        self.parent_id = parent_id  # lineage tracking
        self.args = args or []
        self.alive = True
        self.metadata = {
            "uid": self.uid,
            "parent_id": self.parent_id,
            "args": self.args,
        }

    def quine_self(self):
        """
        Serialize source + metadata to file.
        This simulates the 'modified quineing' process.
        """
        if not os.path.exists(self.BASE_PATH):
            os.makedirs(self.BASE_PATH)
        filename = os.path.join(self.BASE_PATH, f"species_{self.uid}.py")

        # Example source code template (simplified)
        source = f'''\
# Autogenerated ByteWordOntoSpecies code
# uid: {self.uid}
# parent: {self.parent_id}
# args: {self.args}

import sys
import traceback

class ByteWordOntoSpecies:
    def __init__(self, parent_id=None, args=None, uid="{self.uid}"):
        self.uid = uid
        self.parent_id = parent_id
        self.args = args or []
        self.alive = True

    def run(self):
        print("Running species {self.uid} with args:", self.args)
        # Simulate survival condition
        if "fail" in self.args:
            raise RuntimeError("Simulated failure in species {self.uid}")

    def __exit__(self, exc_type, exc_value, tb):
        print(f"Cleaning up species {self.uid}")
        if exc_type:
            print("Exception:", exc_value)
        self.alive = False

if __name__ == "__main__":
    try:
        instance = ByteWordOntoSpecies(parent_id="{self.parent_id}", args={self.args}, uid="{self.uid}")
        instance.run()
    except Exception:
        traceback.print_exc()
        sys.exit(1)
'''

        with open(filename, "w") as f:
            f.write(source)

        print(f"Species {self.uid} quined itself to {filename}")
        return filename

    def spawn_child(self, args=None):
        """
        Fork a child species with given args.
        The child will inherit lineage info.
        """
        child = ByteWordOntoSpecies(parent_id=self.uid, args=args)
        filename = child.quine_self()

        # In a full runtime, you'd now exec or subprocess run that file with args
        # Here we just simulate
        print(f"Spawned child species {child.uid} from parent {self.uid}")
        return child

    def exit(self):
        """
        Lifecycle exit call — triggers cleanup
        """
        self.alive = False
        print(f"Species {self.uid} exiting cleanly.")

# Demonstration main


def main():
    # Parent species
    parent = ByteWordOntoSpecies(args=["init"])
    parent.quine_self()

    # Spawn a child with 'fail' to trigger failure
    child = parent.spawn_child(args=["fail"])

    # Simulate child lifecycle management
    try:
        child.run()
    except Exception as e:
        print(f"Child species {child.uid} failed with error:", e)
        child.exit()


if __name__ == "__main__":
    main()
